name: Delete All Files

on:
  push:
    branches:
      - main

jobs:
  delete_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete all files
        run: |
          rm -rf *
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Delete all files"
          git push
